
server:
  port: 5555

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
  routes:
    # ?? ?? ??  http://localhost:5555/srve2/v1/~~
    service2: /srve2/**

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"